import test from 'node:test';
import assert from 'node:assert/strict';
import { createSimulator } from './server.mjs';

async function withServer(callback){const {server}=createSimulator();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();try{await callback(`http://127.0.0.1:${address.port}`)}finally{await new Promise(resolve=>server.close(resolve))}}

test('serves the embedded dashboard and CaskLogic asset',()=>withServer(async base=>{const page=await fetch(base);assert.equal(page.status,200);assert.match(await page.text(),/Laveggio Printomatic/);const logo=await fetch(`${base}/casklogicmark.png`);assert.equal(logo.status,200);assert.equal(logo.headers.get('content-type'),'image/png')}));

test('status contract exposes stable full snapshot and diagnostics',()=>withServer(async base=>{const response=await fetch(`${base}/api/status`);assert.equal(response.status,200);const status=await response.json();assert.deepEqual(status.snapshot.digits,[1,2,3,4]);assert.equal(status.snapshot.weight_kg,12340);assert.equal(status.sensors.length,4);assert.equal(status.storage.ready,true);assert.equal(status.network.connected,true)}));

test('display state can be changed remotely',()=>withServer(async base=>{const body=new URLSearchParams({enabled:'true'});assert.equal((await fetch(`${base}/api/display`,{method:'POST',body})).status,200);const status=await (await fetch(`${base}/api/status`)).json();assert.equal(status.display_on,true)}));

test('calibration capture persists the selected detent',()=>withServer(async base=>{const body=new URLSearchParams({channel:'2',position:'8'});const saved=await (await fetch(`${base}/api/calibration/capture`,{method:'POST',body})).json();assert.equal(saved.ok,true);const calibration=await (await fetch(`${base}/api/calibration`)).json();assert.equal(calibration.channels[2].points[8].enabled,true);assert.equal(calibration.channels[2].points[8].raw,saved.raw)}));

test('blank secret fields do not overwrite configured values',()=>withServer(async base=>{const first=new URLSearchParams({device_id:'laveggio-02',backend_url:'http://backend/events',backend_token:'secret',notification_url:'',stable_ms:'800',heartbeat_seconds:'45'});await fetch(`${base}/api/settings/integration`,{method:'POST',body:first});const second=new URLSearchParams({device_id:'laveggio-02',backend_url:'http://backend/events',backend_token:'',notification_url:'',stable_ms:'800',heartbeat_seconds:'45'});await fetch(`${base}/api/settings/integration`,{method:'POST',body:second});const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(settings.backend_token,'secret');assert.equal(settings.stable_ms,800)}));

test('invalid calibration coordinates are rejected',()=>withServer(async base=>{const response=await fetch(`${base}/api/calibration/capture`,{method:'POST',body:new URLSearchParams({channel:'9',position:'2'})});assert.equal(response.status,400);assert.match((await response.json()).error,/non validi/)}));

test('calibration reset clears all ten detents on one channel',()=>withServer(async base=>{const response=await fetch(`${base}/api/calibration/reset`,{method:'POST',body:new URLSearchParams({channel:'1'})});assert.equal(response.status,200);const calibration=await (await fetch(`${base}/api/calibration`)).json();assert.equal(calibration.channels[1].points.every(point=>!point.enabled&&point.raw===0),true);assert.equal(calibration.channels[0].points.some(point=>point.enabled),true)}));

test('network and TLS integration settings round-trip through the API',()=>withServer(async base=>{await fetch(`${base}/api/settings/network`,{method:'POST',body:new URLSearchParams({wifi_ssid:'Pesa',wifi_password:'wifi-secret',use_dhcp:'true',static_ip:'10.0.0.90',gateway:'10.0.0.1',subnet:'255.255.255.0',dns:'10.0.0.1'})});await fetch(`${base}/api/settings/integration`,{method:'POST',body:new URLSearchParams({device_id:'laveggio-03',backend_url:'https://casklogic.test/api/v1/scale-devices/events',backend_token:'device-secret',tls_ca_certificate:'-----BEGIN CERTIFICATE-----\nTEST\n-----END CERTIFICATE-----',notification_url:'https://casklogic.test/power',stable_ms:'900',heartbeat_seconds:'60'})});const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(settings.wifi_ssid,'Pesa');assert.equal(settings.use_dhcp,true);assert.equal(settings.device_id,'laveggio-03');assert.match(settings.tls_ca_certificate,/BEGIN CERTIFICATE/);assert.equal(settings.stable_ms,900)}));

test('history is available as JSON and downloadable NDJSON',()=>withServer(async base=>{const history=await (await fetch(`${base}/api/history?limit=3`)).json();assert.equal(history.items.length,3);const exportResponse=await fetch(`${base}/api/history/export`);assert.equal(exportResponse.status,200);assert.match(exportResponse.headers.get('content-type'),/ndjson/);const lines=(await exportResponse.text()).trim().split('\n');assert.equal(lines.length,12);assert.equal(JSON.parse(lines[0]).type,'scale.snapshot')}));

test('unknown API routes return a structured 404',()=>withServer(async base=>{const response=await fetch(`${base}/api/not-present`);assert.equal(response.status,404);assert.match((await response.json()).error,/non trovato/)}));

test('diagnostic log export contains sensor samples',()=>withServer(async base=>{const response=await fetch(`${base}/api/logs/export`);assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/laveggio-log-completo/);const record=JSON.parse((await response.text()).trim());assert.equal(record.event,'sensor_diagnostics');assert.equal(record.sensors.length,4)}));
