import test from 'node:test';
import assert from 'node:assert/strict';
import { createSimulator } from './server.mjs';

async function withServer(callback){const {server}=createSimulator();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();try{await callback(`http://127.0.0.1:${address.port}`)}finally{await new Promise(resolve=>server.close(resolve))}}
const csrfHeaders={'X-CSRF-Token':'simulator-csrf-token'};
function post(url,body){return fetch(url,{method:'POST',headers:csrfHeaders,body})}

test('serves the PesaLink dashboard, scale name, internal-use notice and CaskLogic asset',()=>withServer(async base=>{const page=await fetch(base);assert.equal(page.status,200);const html=await page.text();assert.match(html,/CaskLogic PesaLink/);assert.match(html,/pesa Laveggio Printomatic/);assert.match(html,/uso interno non fiscale/i);const logo=await fetch(`${base}/casklogicmark.png`);assert.equal(logo.status,200);assert.equal(logo.headers.get('content-type'),'image/png')}));

test('status contract exposes stable full snapshot and diagnostics',()=>withServer(async base=>{const response=await fetch(`${base}/api/status`);assert.equal(response.status,200);const status=await response.json();assert.deepEqual(status.snapshot.digits,[1,2,3,4]);assert.equal(status.snapshot.weight_kg,12340);assert.equal(status.sensors.length,4);assert.equal(status.storage.ready,true);assert.equal(status.network.connected,true)}));

test('display state can be changed remotely and becomes the persisted default',()=>withServer(async base=>{const body=new URLSearchParams({enabled:'false'});assert.equal((await post(`${base}/api/display`,body)).status,200);const status=await (await fetch(`${base}/api/status`)).json();const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(status.display_on,false);assert.equal(settings.display_default_on,false)}));

test('speaker confirmation can be disabled and persists independently from display',()=>withServer(async base=>{const body=new URLSearchParams({enabled:'false'});assert.equal((await post(`${base}/api/speaker`,body)).status,200);const status=await (await fetch(`${base}/api/status`)).json();const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(status.speaker_on,false);assert.equal(status.speaker_ready,true);assert.equal(settings.speaker_default_on,false);assert.equal(status.display_on,true)}));

test('speaker test works without changing the persisted confirmation setting',()=>withServer(async base=>{await post(`${base}/api/speaker`,new URLSearchParams({enabled:'false'}));const response=await post(`${base}/api/speaker/test`,new URLSearchParams());assert.equal(response.status,200);assert.equal((await response.json()).ready,true);const status=await (await fetch(`${base}/api/status`)).json();const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(status.speaker_on,false);assert.equal(settings.speaker_default_on,false)}));

test('speaker test rejects repeated requests while the test sound is finishing',()=>withServer(async base=>{assert.equal((await post(`${base}/api/speaker/test`,new URLSearchParams())).status,200);const repeated=await post(`${base}/api/speaker/test`,new URLSearchParams());assert.equal(repeated.status,429);assert.match((await repeated.json()).error,/fine del bip/)}));

test('speaker volume is validated and exposed by settings and status',()=>withServer(async base=>{const saved=await post(`${base}/api/speaker/volume`,new URLSearchParams({volume:'35'}));assert.equal(saved.status,200);assert.equal((await saved.json()).volume,35);const settings=await (await fetch(`${base}/api/settings`)).json();const status=await (await fetch(`${base}/api/status`)).json();assert.equal(settings.speaker_volume_percent,35);assert.equal(status.speaker_volume_percent,35);assert.equal((await post(`${base}/api/speaker/volume`,new URLSearchParams({volume:'101'}))).status,400);assert.equal((await post(`${base}/api/speaker/volume`,new URLSearchParams({volume:'forte'}))).status,400)}));

test('versioned web assets are never reused from an older firmware',()=>withServer(async base=>{const page=await (await fetch(`${base}/`)).text();assert.match(page,/app\.css\?v=2\.0\.5/);assert.match(page,/app\.js\?v=2\.0\.5/);assert.equal((await fetch(`${base}/app.js?v=2.0.5`)).headers.get('cache-control'),'no-store');assert.equal((await fetch(`${base}/app.css?v=2.0.5`)).headers.get('cache-control'),'no-store')}));

test('new ESP32-S3 board telemetry exposes touch, IMU, RTC and native battery',()=>withServer(async base=>{const status=await (await fetch(`${base}/api/status`)).json();assert.equal(status.board.model,'Waveshare ESP32-S3-Touch-LCD-2.8');assert.equal(status.board.touch_controller,'CST3530');assert.equal(status.board.imu_available,true);assert.equal(status.board.rtc_valid,true);assert.equal(status.power.battery_present,true);assert.equal(status.power.battery_voltage_mv,4028)}));

test('calibration capture persists the selected detent',()=>withServer(async base=>{const body=new URLSearchParams({channel:'2',position:'8'});const saved=await (await post(`${base}/api/calibration/capture`,body)).json();assert.equal(saved.ok,true);const calibration=await (await fetch(`${base}/api/calibration`)).json();assert.equal(calibration.channels[2].points[8].enabled,true);assert.equal(calibration.channels[2].points[8].raw,saved.raw)}));

test('blank secret fields do not overwrite configured values',()=>withServer(async base=>{const common={device_id:'pesalink-02',backend_url:'https://backend/events',tls_ca_certificate:'CA',notification_url:'',stable_ms:'800',heartbeat_seconds:'45'};await post(`${base}/api/settings/integration`,new URLSearchParams({...common,backend_token:'secret'}));await post(`${base}/api/settings/integration`,new URLSearchParams({...common,backend_token:''}));const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(settings.backend_token,'secret');assert.equal(settings.stable_ms,800)}));

test('invalid calibration coordinates are rejected',()=>withServer(async base=>{const response=await post(`${base}/api/calibration/capture`,new URLSearchParams({channel:'9',position:'2'}));assert.equal(response.status,400);assert.match((await response.json()).error,/non validi/)}));

test('calibration reset clears all ten detents on one channel',()=>withServer(async base=>{const response=await post(`${base}/api/calibration/reset`,new URLSearchParams({channel:'1'}));assert.equal(response.status,200);const calibration=await (await fetch(`${base}/api/calibration`)).json();assert.equal(calibration.channels[1].points.every(point=>!point.enabled&&point.raw===0),true);assert.equal(calibration.channels[0].points.some(point=>point.enabled),true)}));

test('network, TLS and mTLS settings round-trip through the API',()=>withServer(async base=>{await post(`${base}/api/settings/network`,new URLSearchParams({wifi_ssid:'Pesa',wifi_password:'wifi-secret',use_dhcp:'true',static_ip:'10.0.0.90',gateway:'10.0.0.1',subnet:'255.255.255.0',dns:'10.0.0.1'}));await post(`${base}/api/settings/integration`,new URLSearchParams({device_id:'pesalink-03',backend_url:'https://casklogic.test/api/v1/scale-devices/events',backend_token:'device-secret',tls_ca_certificate:'-----BEGIN CERTIFICATE-----\nTEST\n-----END CERTIFICATE-----',tls_client_certificate:'CLIENT CERT',tls_client_private_key:'PRIVATE KEY',notification_url:'https://casklogic.test/power',stable_ms:'900',heartbeat_seconds:'60',heartbeat_watchdog_enabled:'true',heartbeat_failure_threshold:'5'}));const settings=await (await fetch(`${base}/api/settings`)).json();assert.equal(settings.wifi_ssid,'Pesa');assert.equal(settings.use_dhcp,true);assert.equal(settings.device_id,'pesalink-03');assert.match(settings.tls_ca_certificate,/BEGIN CERTIFICATE/);assert.equal(settings.tls_client_key_configured,true);assert.equal(settings.heartbeat_watchdog_enabled,true)}));

test('history defaults to 20 and filtered export matches the active filter',()=>withServer(async base=>{const initial=await (await fetch(`${base}/api/history`)).json();assert.equal(initial.items.length,20);const query='delivery=requested&sort=weight_kg&direction=asc';const history=await (await fetch(`${base}/api/history?${query}`)).json();assert.equal(history.items.length,1);assert.equal(history.items[0].delivery,'requested');assert.equal(typeof history.items[0].signature,'string');const exportResponse=await fetch(`${base}/api/history/export?${query}`);assert.equal(exportResponse.status,200);assert.match(exportResponse.headers.get('content-type'),/ndjson/);const lines=(await exportResponse.text()).trim().split('\n');assert.equal(lines.length,1);assert.equal(JSON.parse(lines[0]).delivery,'requested')}));

test('history sort returns only the first 20 rows in the selected global order',()=>withServer(async base=>{const history=await (await fetch(`${base}/api/history?sort=weight_kg&direction=asc`)).json();assert.equal(history.items.length,20);assert.equal(history.items[0].weight_kg,11870);assert.equal(history.items.every((row,index,rows)=>index===0||rows[index-1].weight_kg<=row.weight_kg),true)}));

test('security headers and CSRF validation protect the portal',()=>withServer(async base=>{const page=await fetch(base);assert.equal(page.headers.get('x-frame-options'),'DENY');const rejected=await fetch(`${base}/api/display`,{method:'POST',body:new URLSearchParams({enabled:'true'})});assert.equal(rejected.status,403);assert.match((await rejected.json()).error,/CSRF/)}));

test('system status exposes bootstrap credential, VLAN and battery security state',()=>withServer(async base=>{const status=await (await fetch(`${base}/api/status`)).json();assert.equal(status.security.default_credentials_active,true);assert.equal(status.security.vlan_managed_by_network,true);assert.equal(status.power.battery_capacity_mah,1200);assert.equal(status.power.current_sensor_configured,false)}));

test('autodiagnostics and daily charts expose real and unavailable measurements',()=>withServer(async base=>{const run=await post(`${base}/api/diagnostics/run`,new URLSearchParams());assert.equal(run.status,200);const diagnostics=await run.json();assert.equal(diagnostics.active_tests,true);assert.equal(diagnostics.tests.some(item=>item.id==='storage'&&item.status==='pass'),true);const daily=await (await fetch(`${base}/api/diagnostics/daily`)).json();assert.equal(daily.points.length,288);assert.equal(daily.current_available,false);assert.equal(daily.points[0].current_ma,null)}));

test('board autodiagnostics cover touch, speaker, IMU and RTC',()=>withServer(async base=>{const diagnostics=await (await fetch(`${base}/api/diagnostics`)).json();for(const id of ['touch','speaker','imu','rtc'])assert.equal(diagnostics.tests.some(item=>item.id===id&&item.status==='pass'),true)}));

test('support package is a ZIP and excludes credentials and network identity',()=>withServer(async base=>{const response=await fetch(`${base}/api/support-package`);assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'application/zip');const archive=Buffer.from(await response.arrayBuffer());assert.equal(archive.readUInt32LE(0),0x04034b50);assert.equal(archive.includes(Buffer.from('configuration-anonymized.json')),true);assert.equal(archive.includes(Buffer.from('wifi_password')),false);assert.equal(archive.includes(Buffer.from('backend_token')),false);assert.equal(archive.includes(Buffer.from('Distilleria')),false);assert.equal(archive.includes(Buffer.from('192.168.0.42')),false)}));

test('Prometheus metrics expose fleet health without secrets',()=>withServer(async base=>{const response=await fetch(`${base}/api/metrics`);assert.equal(response.status,200);const metrics=await response.text();assert.match(metrics,/pesalink_up 1/);assert.match(metrics,/pesalink_free_heap_bytes/);assert.doesNotMatch(metrics,/Presario|secret/)}));

test('remote configuration sync is versioned and requires explicit configuration',()=>withServer(async base=>{let response=await post(`${base}/api/config/sync`,new URLSearchParams());assert.equal(response.status,502);await post(`${base}/api/settings/integration`,new URLSearchParams({device_id:'pesalink-03',backend_url:'',tls_ca_certificate:'CA',notification_url:'',stable_ms:'600',heartbeat_seconds:'30',heartbeat_failure_threshold:'5',config_sync_enabled:'true',config_sync_url:'https://backend.test/device/config',config_sync_seconds:'900',mqtt_enabled:'false'}));response=await post(`${base}/api/config/sync`,new URLSearchParams());assert.equal(response.status,200);assert.equal((await response.json()).version,1)}));

test('OTA rejects unsigned uploads and records signed updates',()=>withServer(async base=>{let response=await post(`${base}/api/ota`,new URLSearchParams());assert.equal(response.status,400);response=await fetch(`${base}/api/ota`,{method:'POST',headers:{...csrfHeaders,'X-Firmware-Size':'1200000','X-Firmware-Version':'firmware-1.2.1.signed.bin'},body:new URLSearchParams()});assert.equal(response.status,200);const updates=await (await fetch(`${base}/api/firmware/updates`)).json();assert.equal(updates.items[0].signature_verified,true)}));

test('chunked OTA requires ordered complete blocks before restart',()=>withServer(async base=>{const payload=Buffer.alloc(1024,7);let response=await post(`${base}/api/ota/start`,new URLSearchParams({size:String(payload.length),version:'firmware-1.2.8.signed.bin'}));assert.equal(response.status,200);response=await post(`${base}/api/ota/chunk`,new URLSearchParams({offset:'512',data:payload.subarray(0,512).toString('base64')}));assert.equal(response.status,409);response=await post(`${base}/api/ota/chunk`,new URLSearchParams({offset:'0',data:payload.subarray(0,512).toString('base64')}));assert.equal(response.status,200);response=await post(`${base}/api/ota/finish`,new URLSearchParams());assert.equal(response.status,409);response=await post(`${base}/api/ota/chunk`,new URLSearchParams({offset:'512',data:payload.subarray(512).toString('base64')}));assert.equal(response.status,200);response=await post(`${base}/api/ota/finish`,new URLSearchParams());assert.equal(response.status,200);assert.equal((await response.json()).restart_required,true)}));

test('plain HTTP integration endpoints are rejected',()=>withServer(async base=>{const response=await post(`${base}/api/settings/integration`,new URLSearchParams({backend_url:'http://unsafe.local/events',tls_ca_certificate:'CA'}));assert.equal(response.status,400);assert.match((await response.json()).error,/HTTPS/)}));

test('unknown API routes return a structured 404',()=>withServer(async base=>{const response=await fetch(`${base}/api/not-present`);assert.equal(response.status,404);assert.match((await response.json()).error,/non trovato/)}));

test('diagnostic log export contains sensor samples',()=>withServer(async base=>{const response=await fetch(`${base}/api/logs/export`);assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/pesalink-log-completo/);const record=JSON.parse((await response.text()).trim());assert.equal(record.event,'sensor_diagnostics');assert.equal(record.sensors.length,4)}));
