[platformio]
default_envs = waveshare_esp32s3_touch_lcd_28_v2
src_dir = src
include_dir = include
data_dir = data

[env:waveshare_esp32s3_touch_lcd_28_v2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_s3.csv
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=1
  -DUPDATE_SIGN
lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
extra_scripts =
  pre:tools/embed_web_assets.py
  post:tools/sign_firmware.py

[env:waveshare_esp32s3_touch_lcd_28_v1]
extends = env:waveshare_esp32s3_touch_lcd_28_v2
build_flags =
  ${env:waveshare_esp32s3_touch_lcd_28_v2.build_flags}
  -DTOUCH_CST328_PREFERRED=1
